default:
    image: python:3.8.17-slim

stages:
  - test
  - deploy


before_script:
  - apt update && apt install -y gcc
  - pip install .
  - pip install pdoc pytest

unit-test-job:
  stage: test
  script:
    - pytest


pages:
  stage: deploy
  script:
    - pdoc nitrogfx -o public
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH


upload-to-pypi:
  stage : deploy
  script:
    - pip install build twine
    - python3 -m build --sdist
    - twine upload dist/* --username __token__ --password $PYPI_TOKEN
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
