default:
    image: python:3.8.17-slim

stages:
  - test
  - doc


before_script:
  - pip install .
  - pip install pdoc pytest

unit-test-job:
  stage: test
  script:
    - pytest


pages:
  stage: doc
  script:
    - pdoc nitrogfx -o public
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
